config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  # routes pour la table book
  # get 'books', to: 'books#index'
  # post 'books', to: 'books#create'
  # get 'books/new', to: 'books#new'
  # get 'books/:id/edit', to: 'books#edit'
  # get 'books/:id', to: 'books#show', as: :book
  # patch 'books/:id', to: 'books#update'
  # delete 'books/:id', to: 'books#destroy'
  root to: 'pages#home'
  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path
  end

  def edit
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to books_path
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

private
  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :year, :resume, :price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  @members = [ 'Lilia', 'Maewenn', 'Georgia', 'Isabelle' ]
  end

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<div class = container>
  <div class = banner1>
      <h1>Template Livre de Ma Bibliothèque</h1>
  </div>
  <div class = card-trip>
    <%= form_for(book) do |f| %>
      <%= f.label :title  %>
      <%= f.text_field :title %>
      <br>
      <br>
      <%= f.label :author %>
      <%= f.text_field :author %>
      <br>
      <br>
      <%= f.label :year   %>
      <%= f.number_field :year %>
      <br>
      <br>
      <%= f.label :resume %>
      <%= f.text_field :resume %>
      <br>
      <br>
      <%= f.label :price  %>
      <%= f.number_field :price %>
      <br>
      <br>
      <%= f.submit 'submit book', class: 'btn btn-gradient' %>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<%= render 'form', book: @book %>

app/views/books/index.html.erb
<div class = container>
  <div class = banner1>
    <h1>Liste des Livres dans Ma Bibliothèque</h1>
  </div>
  <% montant = 0 %>
    <% @books.each do |book| %>
      <div class = card-trip>
        <h2>Titre    :  <%= book.title %></h2>
        <h2>Year     :  <%= book.year %></h2>
        <h2>Price    :  <%= book.price %>€</h2>
        <% montant += book.price %>
        <%= link_to 'book details', book_path(book), class: 'btn btn-gradient' %>
        <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-gradient' %>
      </div>

    <% end %>

    <div class = card-choice>
      <h2> Total prix <%= montant %> €</H2>
      <%= link_to 'New Book', new_book_path, class: 'btn btn-gradient' %>
      <%= link_to "Back to Home", home_path, class: 'btn btn-gradient' %>
      <%= link_to "Know more about us", about_path, class: 'btn btn-gradient' %>
    </div>
</div>

app/views/books/new.html.erb
<div class = container>
  <div class = card-form>
    <%= render 'form', book: @book %>
  </div>
</div>

app/views/books/show.html.erb
<div class = container>
  <div class = banner1>
      <h1>Détail Livre de Ma Bibliothèque</h1>
  </div>
  <div class = card-trip>
    <h2><%= @book.title %></h2>
    <p><%= @book.author %></p>
    <p><%= @book.year %></p>
    <p><%= @book.resume %></p>
    <p><%= @book.price %>€</p>
    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-gradient'  %>
    <%= link_to 'book delete',
      book_path(@book), class: 'btn btn-gradient' ,
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
    <%= link_to 'book list', books_path, class: 'btn btn-gradient'  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sitest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our sitest about view 🚀</h1>

<%= link_to "Back to Home", home_path %>
<%= link_to "Meet our team", contact_path %>

app/views/pages/contact.html.erb
<h1>Our sitest contact view 🚀</h1>

<h2>Meet our team</h2>
<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

<%= link_to "Back to Home", home_path %>
<%= link_to "Know more about us", about_path %>

app/views/pages/home.html.erb
<div class='banner'd-flex>
  <h1>Our sitest home view 🚀</h1>
  <p>Now is <%= Time.now %></p>
  <%= link_to "Know more about us", about_path, class: 'btn btn-gradient' %>
  <%= link_to "Meet our team", contact_path, class: 'btn btn-gradient' %>
  <%= link_to 'book list', books_path, class: 'btn btn-gradient' %>
</div>